### PR TITLE
Kafka processor

### PR DESCRIPTION
**Pull request by RoySegall**
I managed to connect Kafka to the flow:
Hnet com-image

I've added new packages but when firing the container they are not being installed though I rebuild the container.

@ItamarGronich ^^

### CODE REVIEW

**Comment by ItamarGronich** [comment]
Try to run with `docker-compose up -d --force-recreate`

**Comment by RoySegall** [comment]
When we deploy it to docker hub do we have the `--force-recreate` flag?

**Comment by RoySegall** [comment]
@ItamarGronich Beside that, what about do you think about the topics?

**Comment by ItamarGronich** [comment]
When we deploy we use kubernetes. Docker compose is just for development. So it's a different story.


Let's discuss the topics with the rest of the gang.

**Pull request closed without merging**
