### PR TITLE
add usehash routing strategy

### PR DESCRIPTION
**Pull request by shootermv**
**What kind of change does this PR introduce?** (check _one_ with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Docs related changes
[ ] Other... Please describe:
```

**Link to the open issue**:

**Other information**:

### CODE REVIEW

**Comment by RoySegall** [comment]
@shootermv Do you think can write a test for that? Keep in mind that the test needs to fail without your fix and when re-adding it the test will pass.

**Comment by shootermv** [comment]
Do you mean e2e test?

**Comment by ItamarGronich** [comment]
This wont solve the problem. It's unrelated.
Also, we don't want hash-bang navigation.

**Comment by shootermv** [comment]
> This doesn't solve the problem.
> Although this works, the underlying problem still remains.
> 
> The problem is in django.
> The thing is, NGINX will forward any request that it doesn't find a static file for to django.
> 
> Django has a `urls.py` file that declares each route and what to do with it (what function to call).
> The problem happens for example when reloading routes that aren't declared in `urls.py` django.
> For example the `/pai` route. This route isn't declared in `urls.py` and when you reload the page, what happens is that NGINX gets that request, can't find any matching files, forwards it to django and django doesn't have any url route defined in `urls.py` for that route.
> 
> What we need to do is one of two things.
> 
> 1. have only a few well defined django routes and have NGINX froward to them specifically (preferred option)
> 2. Have django grab everything `/*` and logically deal with it. less preferred.

Hi Itamar - first of all: you right about all the things above.
But! **Please** - i want you to build the image "hasadna/open-pension-client"  using my PR's branch and run docker-compose up - until you see the project running and it has "#" inside url.  When project is running - try to refresh. I want to be sure that problem remains

**Comment by ItamarGronich** [comment]
@shootermv I've checked and the hashbang url indeed does work.
Again. We should choose the other way.

**Comment by ItamarGronich** [comment]
Already merged in another pr

**Pull request closed without merging**
