### PR TITLE
[WIP] Add flex layout to the project

### PR DESCRIPTION
**Pull request by DavidBronfen**
#299

### CODE REVIEW

**Comment by nirgn975** [comment]
@DavidBronfen Do a re-roll (checkout to master, update your master, checkout to your branch, and merge master to your branch)

**Comment by DavidBronfen** [comment]
@nirgn975 What is the min width we should support?

**Comment by nirgn975** [comment]
@DavidBronfen I don't know :)

**Comment by DavidBronfen** [comment]
@nirgn975 OK so, for now, I'll leave the header in this situation.

Screen width  1047px:
open_pension_

Screen width 1044px:
open_pension_

When we'll know what devices we should support we can fix this as a follow up issue.

**Comment by DavidBronfen** [comment]
@ItamarGronich So I know you made all the aspect ratio thing for the pai component, now I think I need your help to make it responsive.
We added the [flex layout](https://github.com/angular/flex-layout/wiki) library to control the component flexibility.
 Please if you can explain what is going on [here](https://github.com/hasadna/open_pension/pull/350/files#diff-cdd5e1c402235fdc3566143d346eea1bL12):
```scss
transform: translate(3%, 0);
@include aspectRatio(1,1);
```

Can we add a percentage width and height to the svg I think it can resolve the problem here.
Any other suggestions?

**Comment by ItamarGronich** [comment]
Well yes i do. 
There are a couple of things here. 
Firstly I'll say that my PR for making the graph responsive was half done. 
What is missing, and i think we will not be able to avoid, is using JS in the pai controller to edit on the fly some parameters on the SVG element of the pai chart.

#### I'll explain what i did: 
In my PR I've introduced an aspect ratio `@mixin` that will create a `::before` element that will have a padding bottom that'll force the element which it is applied to the provided aspect ratio.
For example this:
```scss 
div {
  @include aspectRatio(3,4);
  width: 30px;
}
```
will result in: 
```scss 
div {
  width: 30px;
}

div::before {
  padding-bottom: 40px;
}
```

Effectively creating an element which when supplied a width will automatically scale by the provided aspect ratio.

What I thought will happen is that I'll create a wrapper around the pai svg element, use the mixin to create a 1:1 aspect ratio element around it and the pai will re-scale itself responsively when that wrapper element will change it's size.

#### So, what's the problem ? what's still left to do ?:
The problem here is that the graph itself (SVG element) doesn't re-scale itself automatically on any event but the event of changing attributes on the SVG element.

Those attributes it listens to are: 
- `width`
- `height`
- `viewBox`

What we need to do is:
Create a piece of Javascript in the pai controller that listens to resizing of the pai container and then edits those properties of the SVG element accordingly. 
`width` and `height` are kind of straight forward. But `veiwBox` is not so much, it needs some experimentation. kinda looks like this.

```html
<svg width="400" height="400" viewBox="0 0 500 500">
</svg>
```
What this means is that viewBox will create a coordinate system on the svg that starts at (0,0) and will span up to (500,500). Those numbers represent and imaginary svg unit. it just divides that svg element by that number equally to calculate those units.
As the element scales down, we will have to scale that number down accordingly. 
I really think that you will mostly understand this better if you experiment a bit with `viewBox`

--- 

Well I hope this clears things up a bit. 

If you have further questions feel free to ask.

**Comment by nirgn975** [comment]
@DavidBronfen The `package-lock.json` file is now OK, don't delete it, leave it there..

**Comment by DavidBronfen** [comment]
@nirgn975 So all the app is responsive the tests are green just the codevov make some problems.
Please review this PR in order to continue to the next issue.

**Pull request merged**
