### PR TITLE
Temp processor

### PR DESCRIPTION
**Pull request by ItamarGronich**
WIP on trying to make the processor work with docker and docker compose.

### CODE REVIEW

**Comment by ItamarGronich** [comment]
@RoySegall It works now.
I tried to connect to the DB manually from container and succeeded!
But somehow, the code still can't connect to the DB.
I think the problem is because it tries to connect before the DB is listening.
Maybe we need to check that the DB is available before we launch the server ?

**Comment by RoySegall** [comment]
Hmmm.. I don't think because when initing the connection in [here](https://github.com/hasadna/open_pension/blob/9434e717e71f11b9fe0c1fa4295b04640c9dd020/processor/src/app/mongodb.py#L9) we waited for the connection to establish.

**Comment by ItamarGronich** [comment]
@RoySegall I made it work.

**Comment by RoySegall** [comment]
when trying to test this one I'm getting the next error while trying to parse a file:
```
app.exceptions.FailToLoadFile: Failed to load excel file - /app/app/files/uploaded/work_1570280933.xlsx
processor_1  | 
processor_1  | During handling of the above exception, another exception occurred:
processor_1  | 
processor_1  | Traceback (most recent call last):
processor_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
processor_1  |     rv = self.dispatch_request()
processor_1  |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
processor_1  |     return self.view_functions[rule.endpoint](**req.view_args)
processor_1  |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
processor_1  |     resp = resource(*args, **kwargs)
processor_1  |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 89, in view
processor_1  |     return self.dispatch_request(*args, **kwargs)
processor_1  |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
processor_1  |     resp = meth(*args, **kwargs)
processor_1  |   File "./app/resources.py", line 94, in patch
processor_1  |     results = parser.parse(process_item['path'])
processor_1  |   File "./app/parser.py", line 47, in parse
processor_1  |     raise ExcelWorkbookParsingError(parse_error=errors, file_name=file_path)
processor_1  | app.exceptions.ExcelWorkbookParsingError
```

**Comment by ItamarGronich** [comment]
@RoySegall Ah, i didn't try to test.
Just made it work with dev/prod and connect to db

**Pull request merged**
