### PR TITLE
Bring back the processor service

### PR DESCRIPTION
**Pull request by RoySegall**
Don't know why it was removed,  but I need this one so we could kick off all the process of the files.

### CODE REVIEW

**Comment by 0x217** [comment]
I working on processor (dev_ron branch), I will finish the service soon and then you can put your changes.

**Comment by RoySegall** [comment]
How should I know that if there's no PR? I think I mentioned that before but - when you push a branch with a work create a PR so anyone of us could use that or continue the work.

About the name of the branch - the name `dev_ron` is not a proper name for a branch. A branch name should clear the purpose of the branch. A good name, for example, is the number of the issue which the branch intended to solve or something like `file-process-service`. But the number of the branch is better.

Please rename the branch and create a PR.

**Comment by 0x217** [comment]
The name of branch is dev_ron_processor

בתאריך יום ב׳, 10 ביוני 2019, 8:33, מאת Roy Segall ‏<
notifications@github.com>:

**Comment by ItamarGronich** [comment]
@0x217 is going to implement this in his branch as he said in [this comment](https://github.com/hasadna/open_pension/pull/458#issuecomment-500303746)

**Comment by ItamarGronich** [comment]
@0x217 is going to implement this in his branch as he said in [this comment](https://github.com/hasadna/open_pension/pull/458#issuecomment-500303746)

**Pull request closed without merging**
